export default function NewDesign(){
    return (
       <div id="newDesign">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Accumsan sit amet nulla facilisi. Velit egestas dui id ornare arcu odio ut. Nulla pellentesque dignissim enim sit amet venenatis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Facilisis leo vel fringilla est ullamcorper eget nulla. Commodo nulla facilisi nullam vehicula. Sed felis eget velit aliquet sagittis id consectetur purus. Hendrerit dolor magna eget est lorem. Orci phasellus egestas tellus rutrum. Tristique risus nec feugiat in fermentum posuere urna nec. Id volutpat lacus laoreet non. Sapien pellentesque habitant morbi tristique senectus. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Diam donec adipiscing tristique risus nec feugiat. Urna molestie at elementum eu facilisis sed odio morbi. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Sed euismod nisi porta lorem mollis aliquam. Condimentum mattis pellentesque id nibh tortor id. Leo a diam sollicitudin tempor.

Viverra adipiscing at in tellus integer feugiat. Integer vitae justo eget magna. Laoreet suspendisse interdum consectetur libero id. Interdum varius sit amet mattis vulputate. Bibendum est ultricies integer quis auctor elit. Odio tempor orci dapibus ultrices in. At risus viverra adipiscing at. In dictum non consectetur a erat nam at. Tristique magna sit amet purus. Bibendum arcu vitae elementum curabitur vitae nunc sed velit dignissim. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean.

Orci ac auctor augue mauris augue neque. <span id="span_text">Quam vulputate dignissim suspendisse in est ante in nibh mauris. Varius vel pharetra vel turpis nunc eget lorem dolor.</span> Luctus accumsan tortor posuere ac ut consequat. Posuere sollicitudin aliquam ultrices sagittis orci. Sed turpis tincidunt id aliquet risus feugiat. Mattis aliquam faucibus purus in massa. Nec feugiat in fermentum posuere urna nec. Quam id leo in vitae. Suscipit tellus mauris a diam maecenas. Nullam ac tortor vitae purus faucibus ornare suspendisse. Tellus mauris a diam maecenas sed enim. Dignissim suspendisse in est ante.

Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nam at lectus urna duis convallis convallis tellus. Enim eu turpis egestas pretium. Placerat vestibulum lectus mauris ultrices eros. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Et malesuada fames ac turpis egestas sed tempus urna. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Maecenas sed enim ut sem viverra aliquet eget sit amet. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Vehicula ipsum a arcu cursus vitae. Sed cras ornare arcu dui. Bibendum at varius vel pharetra vel turpis nunc. Sem viverra aliquet eget sit amet tellus cras. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Dui id ornare arcu odio ut sem nulla pharetra diam.
        
       </div>
    )
}